// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uWDd2Z7LdZq3S9M3cRlqto-9JFQr9qA',
    appId: '1:829681305965:web:fd76e973cdfc93dbaa7264',
    messagingSenderId: '829681305965',
    projectId: 'chat-app-4d94c',
    authDomain: 'chat-app-4d94c.firebaseapp.com',
    storageBucket: 'chat-app-4d94c.appspot.com',
    measurementId: 'G-SPLPBRHTYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uXWVIO3VOuVS1p3L-FJUvet_xey3jPw',
    appId: '1:829681305965:android:6a5759c0ec33b0a2aa7264',
    messagingSenderId: '829681305965',
    projectId: 'chat-app-4d94c',
    storageBucket: 'chat-app-4d94c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-U8WpvJJbI5zBQDxTLKSRceYyooFSfQ',
    appId: '1:829681305965:ios:d77dde0b2ff58220aa7264',
    messagingSenderId: '829681305965',
    projectId: 'chat-app-4d94c',
    storageBucket: 'chat-app-4d94c.appspot.com',
    iosClientId: '829681305965-7757aiv0apbbpaaj9uvaco1vusss2d4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-U8WpvJJbI5zBQDxTLKSRceYyooFSfQ',
    appId: '1:829681305965:ios:d77dde0b2ff58220aa7264',
    messagingSenderId: '829681305965',
    projectId: 'chat-app-4d94c',
    storageBucket: 'chat-app-4d94c.appspot.com',
    iosClientId: '829681305965-7757aiv0apbbpaaj9uvaco1vusss2d4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
